name: module_app_services

services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    networks:
      - app_network

  monitor:
    image: mongo-express
    container_name: monitor
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@database:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: "user"           # Basic auth username
      ME_CONFIG_BASICAUTH_PASSWORD: "password"       # Basic auth password
    depends_on:
      - database
    networks:
      - app_network

  dld-express-api:
    image: duyleduc520/apiservice:latest
    container_name: dld-express-api
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://root:example@database:27017/
      MONGODB_NAME: app
      MONGODB_COLL: module_app
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
